import React from "react";

export const cafes = [
  {
    name: "Nestle Hotspot",
    color: "bg-primary-red",
    menu: [
      {
        name: "Maggi",
        price: "45",
        buttonColor: "bg-primary-red",
        image: "./assets/maggie.jpeg",
      },
      {
        name: "Butter Maggi",
        price: "55",
        buttonColor: "bg-primary-red",
        image: "./assets/maggie.jpeg",
      },
      {
        name: "Masala Maggi",
        price: "50",
        buttonColor: "bg-primary-red",
        image: "./assets/maggie.jpeg",
      },
      {
        name: "Garlic Maggi",
        price: "60",
        buttonColor: "bg-primary-red",
        image: "./assets/maggie.jpeg",
      },
      {
        name: "Peri Peri Maggi",
        price: "55",
        buttonColor: "bg-primary-red",
        image: "./assets/maggie.jpeg",
      },
      {
        name: "Oregano Maggi",
        price: "65",
        buttonColor: "bg-primary-red",
        image: "./assets/maggie.jpeg",
      },
      {
        name: "Milky Bar",
        price: "20",
        buttonColor: "bg-primary-red",
        image: "./assets/maggie.jpeg",
      },
      {
        name: "Kit Kat",
        price: "30",
        buttonColor: "bg-primary-red",
        image: "./assets/maggie.jpeg",
      },
      {
        name: "Sandwich",
        price: "65",
        buttonColor: "bg-primary-red",
        image: "./assets/maggie.jpeg",
      },
      {
        name: "Truffle",
        price: "70",
        buttonColor: "bg-primary-red",
        image: "./assets/maggie.jpeg",
      },
    ],
  },
  {
    name: "Southern Stories",
    color: "bg-primary-beige",
    menu: [
      {
        name: "Plain Dosa",
        price: "80",
        buttonColor: "bg-primary-beige",
        image: "./assets/dosa.jpeg",
      },
      {
        name: "Malsal Dosa",
        price: "90",
        buttonColor: "bg-primary-beige",
        image: "./assets/dosa.jpeg",
      },
      {
        name: "Rava Dosa",
        price: "100",
        buttonColor: "bg-primary-beige",
        image: "./assets/dosa.jpeg",
      },
      {
        name: "Rava Masala Dosa",
        price: "110",
        buttonColor: "bg-primary-beige",
        image: "./assets/dosa.jpeg",
      },
      {
        name: "Aloo Paratha",
        price: "110",
        buttonColor: "bg-primary-beige",
        image: "./assets/dosa.jpeg",
      },
      {
        name: "Paneer Paratha",
        price: "120",
        buttonColor: "bg-primary-beige",
        image: "./assets/dosa.jpeg",
      },
      {
        name: "Mixed Paratha",
        price: "140",
        buttonColor: "bg-primary-beige",
        image: "./assets/dosa.jpeg",
      },
      {
        name: "Laccha Paratha",
        price: "120",
        buttonColor: "bg-primary-beige",
        image: "./assets/dosa.jpeg",
      },
      {
        name: "Cold Drink",
        price: "40",
        buttonColor: "bg-primary-beige",
        image: "./assets/dosa.jpeg",
      },
      {
        name: "Idli",
        price: "60",
        buttonColor: "bg-primary-beige",
        image: "./assets/dosa.jpeg",
      },
    ],
  },
  {
    name: "Cafe One",
    color: "bg-primary-blue",
    menu: [
      {
        name: "Egg Roll",
        price: "80",
        buttonColor: "bg-primary-orange",
        image: "./assets/chole.png",
      },
      {
        name: "Paneer Shawarma",
        price: "95",
        buttonColor: "bg-primary-orange",
        image: "./assets/chole.png",
      },
      {
        name: "Paneer Tikka Roll",
        price: "100",
        buttonColor: "bg-primary-orange",
        image: "./assets/chole.png",
      },
      {
        name: "Paneer Makhani Roll",
        price: "110",
        buttonColor: "bg-primary-orange",
        image: "./assets/chole.png",
      },
      {
        name: "Paneer Bhurji Roll",
        price: "100",
        buttonColor: "bg-primary-orange",
        image: "./assets/chole.png",
      },
      {
        name: "Paneer Schezwan Roll",
        price: "110",
        buttonColor: "bg-primary-orange",
        image: "./assets/chole.png",
      },
      {
        name: "Paneer Egg Roll",
        price: "100",
        buttonColor: "bg-primary-orange",
        image: "./assets/chole.png",
      },
      {
        name: "Noodles Roll",
        price: "85",
        buttonColor: "bg-primary-orange",
        image: "./assets/chole.png",
      },
      {
        name: "Soya Chap Roll",
        price: "85",
        buttonColor: "bg-primary-orange",
        image: "./assets/chole.png",
      },
      {
        name: "Creamy Soya Roll",
        price: "100",
        buttonColor: "bg-primary-orange",
        image: "./assets/chole.png",
      },
    ],
  },
  {
    name: "Quench",
    color: "bg-primary-green",
    menu: [
      {
        name: "Peri Peri Fries",
        price: "60",
        buttonColor: "bg-primary-green",
        image: "./assets/fries.png",
      },
      {
        name: "Plain Fries",
        price: "50",
        buttonColor: "bg-primary-green",
        image: "./assets/fries.png",
      },
      {
        name: "Aloo Burger",
        price: "40",
        buttonColor: "bg-primary-green",
        image: "./assets/fries.png",
      },
      {
        name: "Schezwan Burger",
        price: "40",
        buttonColor: "bg-primary-green",
        image: "./assets/fries.png",
      },
      {
        name: "Paneer Burger",
        price: "50",
        buttonColor: "bg-primary-green",
        image: "./assets/fries.png",
      },
      {
        name: "Veggie Burger",
        price: "60",
        buttonColor: "bg-primary-green",
        image: "./assets/fries.png",
      },
      {
        name: "Crispy Burger",
        price: "70",
        buttonColor: "bg-primary-green",
        image: "./assets/fries.png",
      },
      {
        name: "Crispy Paneer Burger",
        price: "60",
        buttonColor: "bg-primary-green",
        image: "./assets/fries.png",
      },
      {
        name: "Chocolate Shake",
        price: "80",
        buttonColor: "bg-primary-green",
        image: "./assets/fries.png",
      },
      {
        name: "Mango Shake",
        price: "80",
        buttonColor: "bg-primary-green",
        image: "./assets/fries.png",
      },
    ],
  },
  {
    name: "Urban Kitchen",
    color: "bg-primary-orange",
    menu: [
      {
        name: "Dal Makhani",
        price: "240",
        buttonColor: "bg-primary-green",
        image: "./assets/paneer.png",
      },
      {
        name: "Dal Tadka",
        price: "160",
        buttonColor: "bg-primary-green",
        image: "./assets/paneer.png",
      },
      {
        name: "Paneer Butter Masala",
        price: "280",
        buttonColor: "bg-primary-green",
        image: "./assets/paneer.png",
      },
      {
        name: "Paneer Lababdar",
        price: "280",
        buttonColor: "bg-primary-green",
        image: "./assets/paneer.png",
      },
      {
        name: "Shahi Paneer",
        price: "280",
        buttonColor: "bg-primary-green",
        image: "./assets/paneer.png",
      },
      {
        name: "Kadhai Paneer",
        price: "280",
        buttonColor: "bg-primary-green",
        image: "./assets/paneer.png",
      },
      {
        name: "Paneer Dhania Adrak",
        price: "280",
        buttonColor: "bg-primary-green",
        image: "./assets/paneer.png",
      },
      {
        name: "Matar Mushroom",
        price: "280",
        buttonColor: "bg-primary-green",
        image: "./assets/paneer.png",
      },
      {
        name: "Matar Paneer",
        price: "280",
        buttonColor: "bg-primary-green",
        image: "./assets/paneer.png",
      },
      {
        name: "Aloo Jeera",
        price: "H:100 / F:160",
        buttonColor: "bg-primary-green",
        image: "./assets/paneer.png",
      },
    ],
  },
];
